### PR TITLE
Usage: Fix help for https-post-form and https-get-form

### PR DESCRIPTION
**Pull request by Jab2870**
Fixes issue #530

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
thank you!
I rather spend my team teaching you how to do a good fix rather than doing it myself (doing it myself would be 10x faster ;)

your solution is OK, it is not pretty though as you are overwriting the name of the service. but as after the help output hydra exits that is not an issue.

if you implement it like this though - maybe you should also handle other protocols there that share the same issue?
e.g. https-post/get/head ...
and then you could make your solutions easier -> e.g. if it starts with https- then copy the string therafter directly to http- (this can be done with the memove function on the same variable ... memmove(service + 4, service + 5, strlen(service) - 5)

**Comment by Jab2870** [comment]
> I rather spend my team teaching you how to do a good fix rather than doing it myself (doing it myself would be 10x faster ;)

Thank you very much

> your solution is OK, it is not pretty though as you are overwriting the name of the service. but as after the help output hydra exits that is not an issue.

I did wonder if overwriting the name would be an issue, but I saw that the same was done here:

https://github.com/vanhauser-thc/thc-hydra/blob/master/hydra.c#L3113-L3126

I didn't worry about `hydra_options.ssl` because I saw that it ran exit and wasn't used beforehand.

I have made the change you suggested so now any service starting with `https-` will be changed to `http-` for the help section

**Comment by vanhauser-thc** [comment]
did you test it?
because I think I made a mistake with what I wrote. length of menmove should be strlen() - -4 + 1 as otherwise the terminating null byte is not copies too and then the service name has the last character as a double.

**Comment by Jab2870** [comment]
Yes, I tested it and it appears to work.

I did change your code slightly because the last character was duplicated:

```
    memmove(hydra_options.service + 4, hydra_options.service + 5, strlen(hydra_options.service) - 4);
```

**Pull request merged**
