### PR TITLE
fix typo and the offset value of miscptr

### PR DESCRIPTION
**Pull request by rmaksimov**
There should be an offset in the pointer value for everything to work properly

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
thanks for fixing my fuckup

**Comment by vanhauser-thc** [comment]
can you please test that the http module works with the A=BASIC etc. option? So its doing the right thing?

**Comment by rmaksimov** [comment]
Have tested Basic and NTLM, both work fine

**Comment by vanhauser-thc** [comment]
thank you!

**Pull request merged**
