### PR TITLE
New CobaltStrike module

### PR DESCRIPTION
**Pull request by ultimaiiii**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
thanks, I am on vacation, will look at it on monday

**Comment by ultimaiiii** [comment]
No hurry, enjoy!

**Comment by vanhauser-thc** [comment]
looks easy enough. I cant test is though. thanks!

**Comment by vanhauser-thc** [comment]
if you want you can add your module also to xhydra (loot into the hydra-gtk/ subdirectory)

**Comment by ultimaiiii** [comment]
Thanks!

Indeed, it's not difficult.
It looks like this:

image

**Pull request merged**
