### PR TITLE
Add GitHub pages service 

### PR DESCRIPTION
**Pull request by Yisus7u7**
Hello again, github offers a free page service, makes readme files look very nice, and echo the configuration, you just need to enable the service the repository configuration.
Anyway that's not all, there are things to edit but after this the README will be more comfortable with these active topics, and apart from that you will have a web domain.

### CODE REVIEW

**Comment by Yisus7u7** [comment]
Here's a preview of what it will look like, note that if ustef activates the GitHub pages service the domain will have its name and not mine. 

https://yisus7u7.github.io/thc-hydra/

**Comment by vanhauser-thc** [comment]
not really a fan, but I dont mind :) ty.

**Comment by Yisus7u7** [comment]
Well, maybe within an hour you will have all the files ready to merge, save them in a folder called docs

**Comment by Yisus7u7** [comment]
Pd: Please activate the GitHub pages service in settings, so that the domain has your name and not mine

**Comment by vanhauser-thc** [comment]
I think it is online now

**Comment by Yisus7u7** [comment]
Well, leave a check

**Comment by vanhauser-thc** [comment]
but the page is at https://vanhauser-thc.github.io/thc-hydra/ ... and https://vanhauser-thc.github.io/ doesnt exist. well

**Comment by Yisus7u7** [comment]
That's normal, that's github's default domain and changing it costs money, but I don't see that domain wrong anyway.

**Pull request merged**
