### PR TITLE
Add more files to GitHub pages 

### PR DESCRIPTION
**Pull request by Yisus7u7**
@vanhauser-thc
Once the Android part is finished, you can review the changes, accept to apply them.

### CODE REVIEW

**Comment by Yisus7u7** [comment]
I also added an image showing the rest statistics, a perfect decoration for the page on Github pages

**Comment by Yisus7u7** [comment]
My pr's ready to run away, change the GitHub pages theme to a more serious one, you can see its preview here : 

https://yisus7u7.github.io/thc-hydra/

**Comment by vanhauser-thc** [comment]
thank you but I specifically do not want markdown texts. because hydra is not my pet project, but rather something I still maintain because lots of people are using it. I do not like the software very much. and not moving to markdown etc. is one way to show that is is old ... and doesnt get much love :)

**Comment by Yisus7u7** [comment]
Jajajajaja, ok

**Pull request merged**
