### PR TITLE
Rain mode update

### PR DESCRIPTION
**Pull request by e2002e**
Hello, I found a way to have quite the same king of mangling in a way that is understandable.
I got rid of a counter and an if branch throughout the operation, and come up with a strongest, more reliable algorithm (meaning not found by luck).
We are no longer modifyng the selection of the character from the set with a counter that is cut with a modulo, everything comes from the the evolution of the state and I had time enough to enforce the validity of the procedure. 

I did rebase the fork and you are free to examine and pull this, even encouraged to do so because I'm not confident with the last technique even if it seems to render quite the same I had issues with it when implementing in a code, it's not safe to keep it.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
dont have time currently, so didnt review the code yet. 
however you are overwriting the makefile ... so do a make clean and push.

**Comment by e2002e** [comment]
Hallo, ich habe das gemacht, einschuldingung fur mein shclecht deutch. In die schoole ich war soso aber ich habe fergessen weil ich nie mit deutch people schpreche.
Aufwierdersehen !

**Comment by e2002e** [comment]
Ps: I have no intent to mock your language I was just overly joyfull and recelected some of what I learnt in school.
Have a good day vh.

**Comment by e2002e** [comment]
I'm closing, reason is algorithm is not suitable for online brute. See the other pull request.

**Pull request closed without merging**
