### PR TITLE
change long unsigned to long long unsigned

### PR DESCRIPTION
**Pull request by deargle**
Fixes for i686. I admittedly have no idea what the impact of this change would be on Kali x64 systems, but PRing so that you can look if you want to...

See #357

### CODE REVIEW

**Comment by deargle** [comment]
I tested on x64, works fine from what I can tell.

`Linux kali 4.17.0-kali1-amd64 #1 SMP Debian 4.17.8-1kali1 (2018-07-24) x86_64 GNU/Linux`

**Comment by vanhauser-thc** [comment]
Hi, 

the issue with the long long int patch is that it is architecture dependant if its "long long int" or "int" - 64 or 32 bit.
so this patch would just switch the warnings to the other platform.
I think I will switch to #define as this is the only way I see this can work.

**Comment by deargle** [comment]
Sounds good. I am an ultra novice in C, I defer to you. Although I would
note that I never got a warning. Regardless, I'm happy to test whatever you
want to do if you'd like that.

**Comment by dmaciejak** [comment]
Please check the last commit, it's fixing some compilation warning for long unsigned printing that depend on the artchitecture https://github.com/vanhauser-thc/thc-hydra/commit/e1e708d1a1b1b96849e21fb4e9a45fef0e85dfab

**Pull request closed without merging**
