### PR TITLE
V8.8 rain

### PR DESCRIPTION
**Pull request by e2002e**
Here it is, ignore my last pull request please and consider pulling this, cheers :D

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
can you please explain what it does, what it is for?
I dont have much time currently, so trying to understand what code does ...

**Comment by e2002e** [comment]
This is a way to break the linearity of the bruteforce when using bfg, instead of 0000 to 9999 for digits we would have 0136 to 1803, there are no loss nor duplicates, I've called the algorithm 'rain' and the original software "zhou". Check what it looks like [here](https://www.youtube.com/watch?v=BPXbylL3ft4). I was astonished to be able to incorporate it in hydra with a few lines. Cheers

**Comment by vanhauser-thc** [comment]
Hi!

thanks. I am currently busy so I will take care of the beginning of next week I think.
Is the PR done? or are you still testing and changing things?

**Comment by e2002e** [comment]
Ok, the things are all set up, I came up with this piece of code a year ago and it was 'sleeping' on my repo, everything is working and my last commit was just about a typo. I'm glad it can serve and doing the PR now.

**Comment by vanhauser-thc** [comment]
You should never use "long int" as its size differs between 32 <=> 64 bit Unix systems and also between 64 bit Unix and 64 Bit Windows systems :-)

Fixed the stop blockers, now its ready to merge

**Comment by vanhauser-thc** [comment]
Thanks!

**Pull request merged**
